export const featuredAnimals = [
  {
    id: 2,
    name: "Australian Friesian Cow",
    type: "Cow",
    breed: "Friesian",
    price: 180000,
    weight: 350,
    age: 4,
    location: "Dhaka",
    description: "Imported Friesian cow with excellent health and weight.",
    image: "https://i.postimg.cc/s2C2Jbb8/IMG-20221120-WA0010.jpg",
    category: "Large Animal",
    stock: true,
    rating: 4.8,
  },
  {
    id: 5,
    name: "Sahiwal Cow",
    type: "Cow",
    breed: "Sahiwal",
    price: 200000,
    weight: 400,
    age: 5,
    location: "Khulna",
    description: "Premium Sahiwal cow with high meat quality.",
    image: "https://i.postimg.cc/05VbqWJV/IMG-20221120-WA0008.jpg",
    category: "Large Animal",
    stock: false,
    rating: 4.9,
  },
  {
    id: 3,
    name: "Black Bengal Goat",
    type: "Goat",
    breed: "Black Bengal",
    price: 25000,
    weight: 35,
    age: 2,
    location: "Rajshahi",
    description: "Popular Black Bengal goat, very healthy.",
    image: "https://i.postimg.cc/qMgXfCgr/black-bengal-goat.jpg",
    category: "Small Animal",
    stock: true,
    rating: 4.6,
  },
  {
    id: 4,
    name: "Jamunapari Goat",
    type: "Goat",
    breed: "Jamunapari",
    price: 40000,
    weight: 50,
    age: 3,
    location: "Chattogram",
    description: "Large size Jamunapari goat, healthy and strong.",
    image:
      "https://i.postimg.cc/ryHRrZFz/I9g-ONaz61tx0pu-Pe-VLYo-HRlxy-NU.webp",
    category: "Small Animal",
    stock: true,
    rating: 4.7,
  },
];
